/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppIntegracoesRouteImport } from './routes/_app.integracoes'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppClientesIndexRouteImport } from './routes/_app.clientes.index'
import { Route as AppCampanhasIndexRouteImport } from './routes/_app.campanhas.index'
import { Route as AppClientesCustomerIdRouteImport } from './routes/_app.clientes.$customerId'
import { Route as AppCampanhasNovaRouteImport } from './routes/_app.campanhas.nova'
import { Route as AppCampanhasCampaignIdRouteImport } from './routes/_app.campanhas.$campaignId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegracoesRoute = AppIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasIndexRoute = AppCampanhasIndexRouteImport.update({
  id: '/campanhas/',
  path: '/campanhas/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesCustomerIdRoute = AppClientesCustomerIdRouteImport.update({
  id: '/clientes/$customerId',
  path: '/clientes/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasNovaRoute = AppCampanhasNovaRouteImport.update({
  id: '/campanhas/nova',
  path: '/campanhas/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasCampaignIdRoute = AppCampanhasCampaignIdRouteImport.update({
  id: '/campanhas/$campaignId',
  path: '/campanhas/$campaignId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/integracoes': typeof AppIntegracoesRoute
  '/campanhas/$campaignId': typeof AppCampanhasCampaignIdRoute
  '/campanhas/nova': typeof AppCampanhasNovaRoute
  '/clientes/$customerId': typeof AppClientesCustomerIdRoute
  '/campanhas/': typeof AppCampanhasIndexRoute
  '/clientes/': typeof AppClientesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/integracoes': typeof AppIntegracoesRoute
  '/': typeof AppIndexRoute
  '/campanhas/$campaignId': typeof AppCampanhasCampaignIdRoute
  '/campanhas/nova': typeof AppCampanhasNovaRoute
  '/clientes/$customerId': typeof AppClientesCustomerIdRoute
  '/campanhas': typeof AppCampanhasIndexRoute
  '/clientes': typeof AppClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/integracoes': typeof AppIntegracoesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/campanhas/$campaignId': typeof AppCampanhasCampaignIdRoute
  '/_app/campanhas/nova': typeof AppCampanhasNovaRoute
  '/_app/clientes/$customerId': typeof AppClientesCustomerIdRoute
  '/_app/campanhas/': typeof AppCampanhasIndexRoute
  '/_app/clientes/': typeof AppClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/integracoes'
    | '/campanhas/$campaignId'
    | '/campanhas/nova'
    | '/clientes/$customerId'
    | '/campanhas/'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/configuracoes'
    | '/integracoes'
    | '/'
    | '/campanhas/$campaignId'
    | '/campanhas/nova'
    | '/clientes/$customerId'
    | '/campanhas'
    | '/clientes'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/configuracoes'
    | '/_app/integracoes'
    | '/_app/'
    | '/_app/campanhas/$campaignId'
    | '/_app/campanhas/nova'
    | '/_app/clientes/$customerId'
    | '/_app/campanhas/'
    | '/_app/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integracoes': {
      id: '/_app/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AppIntegracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/': {
      id: '/_app/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanhas/': {
      id: '/_app/campanhas/'
      path: '/campanhas'
      fullPath: '/campanhas/'
      preLoaderRoute: typeof AppCampanhasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$customerId': {
      id: '/_app/clientes/$customerId'
      path: '/clientes/$customerId'
      fullPath: '/clientes/$customerId'
      preLoaderRoute: typeof AppClientesCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanhas/nova': {
      id: '/_app/campanhas/nova'
      path: '/campanhas/nova'
      fullPath: '/campanhas/nova'
      preLoaderRoute: typeof AppCampanhasNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanhas/$campaignId': {
      id: '/_app/campanhas/$campaignId'
      path: '/campanhas/$campaignId'
      fullPath: '/campanhas/$campaignId'
      preLoaderRoute: typeof AppCampanhasCampaignIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppIntegracoesRoute: typeof AppIntegracoesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCampanhasCampaignIdRoute: typeof AppCampanhasCampaignIdRoute
  AppCampanhasNovaRoute: typeof AppCampanhasNovaRoute
  AppClientesCustomerIdRoute: typeof AppClientesCustomerIdRoute
  AppCampanhasIndexRoute: typeof AppCampanhasIndexRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppIntegracoesRoute: AppIntegracoesRoute,
  AppIndexRoute: AppIndexRoute,
  AppCampanhasCampaignIdRoute: AppCampanhasCampaignIdRoute,
  AppCampanhasNovaRoute: AppCampanhasNovaRoute,
  AppClientesCustomerIdRoute: AppClientesCustomerIdRoute,
  AppCampanhasIndexRoute: AppCampanhasIndexRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
